version: '3.3'
networks:
  net:
    driver: bridge
volumes:
  data:
services:
  git-server:
    image: marcoshssilvadev/gitserver-ssh:latest
    ports:
    - "22:22"
    volumes:
    - data:/home/git/repository
    networks:
    - net
